---
- name: install nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  yum:
    name: "{{ nginx_version }}"
    state: present

- name: copy nginx main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  when:
    - enable_service_nginx == true

- include: monit.yml
  when:
    - enable_service_nginx == true
  static: false
